### ISSUE TITLE
Make weather display configurable (deactivate, Celsius)

### ISSUE THREAD

**Issue by aetherfaerber** [corbindavenport/planr#2]
Hi, thanks for the nice and useful app!

It would be good to have some additional configurations for the weather display like disabling it altogether to make the message about configuring the location in the main view disappear and also, like someone else already mentioned on FF market, have it display the temperature in Celsius instead of Fahrenheit.

Thanks again!

**Comment by corbindavenport** [comment]
Glad you like Plane! You'll be happy to know I've already implemented a switch for turning on/off the weather card, as well as switching between Fahrenheit and Celsius.

I'm aiming to have the update out by next week :)

**Comment by aetherfaerber** [comment]
Awesome!
Issue closed I guess. (:
